ukf_node:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 1.9
    transform_timeout: 0.5
    publish_tf: true
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    # map_frame: map
    print_diagnostics: true
    two_d_mode: true
    odom0: /odom
    odom0_config: [ true,  true,  false,   # x y z
                    false, false, true,    # roll pitch yaw
                    true,  true,  false,   # vx vy vz
                    false, false, true,    # vroll vpitch vyaw
                    false, false, false ]  # ax ay az
    odom0_differential: true
    odom0_relative:     false
    odom0_queue_size:   10
    odom0_nodelay:      false
    # odom0_rejection_threshold: 100
    # odom1_rejection_threshold: 2.5